### ISSUE TITLE
Csgo update makes the hud buggy 

### ISSUE THREAD

**Issue by freakexeuLow** [StAwN74/ckSurf-1.18kd-Release#1]
hey StAwN74 :) the last Csgo update is unfortunately also the HUD Rip, is it possible that you can fix it?
![20191119093758_1](https://user-images.githubusercontent.com/32603929/69130613-1372c800-0ab1-11ea-8150-a30923a481d8.jpg)

Edit: valvo removed the html shit more Infos: [https://forums.alliedmods.net/showpost.php?p=2673490&postcount=4](https://forums.alliedmods.net/showpost.php?p=2673490&postcount=4)

Edit 2: Fix: [https://forums.alliedmods.net/showthread.php?t=319772](https://forums.alliedmods.net/showthread.php?t=319772)

**Comment by StAwN74** [comment]
Yup freak, thanks Franc1sco!

**Comment by freakexeuLow** [comment]
> 
> 
> Yup freak, thanks Franc1sco!

not really StAwN74...Thanks to Phoenix (˙·٠●Феникс●٠·˙) aka  komashchenko Franzo only removed 2 lines ^^

**Comment by freakexeuLow** [comment]
lul, you can closed the ticket or you implement the Hud Fix on cksurf..I think SurfTimer has already done that (its not a bug, is a feature) :3

**Comment by StAwN74** [comment]
Ok, ticket closed.
