### ISSUE TITLE
Starting the timer creates consistant frame hitching.

### ISSUE THREAD

**Issue by viasux** [StAwN74/ckSurf-1.18kd-Release#10]
Hey! This might not be something you have control over, as it is only persistent on my linux machine, but, whenever I start the map (jump out of the start zone), my game starts consistantly hitching. I'll see if I can send some logs of this issue. I think it would be awesome if this was at least looked at.

**Comment by freakexeuLow** [comment]
> Hey! This might not be something you have control over, as it is only persistent on my linux machine, but, whenever I start the map (jump out of the start zone), my game starts consistantly hitching. I'll see if I can send some logs of this issue. I think it would be awesome if this was at least looked at.

this has as nothing to do with the topic here, why do not you make such a post in the Alliedmodders forum? 
[https://forums.alliedmods.net/showthread.php?t=319662](https://forums.alliedmods.net/showthread.php?t=319662)

[https://forums.alliedmods.net/showthread.php?t=330200](https://forums.alliedmods.net/showthread.php?t=330200)

or make a separate post, please close the topic here and post on Alliedmodders

**Comment by viasux** [comment]
> > Hey! This might not be something you have control over, as it is only persistent on my linux machine, but, whenever I start the map (jump out of the start zone), my game starts consistantly hitching. I'll see if I can send some logs of this issue. I think it would be awesome if this was at least looked at.
> 
> this has as nothing to do with the topic here, why do not you make such a post in the Alliedmodders forum?
> https://forums.alliedmods.net/showthread.php?t=319662
> 
> https://forums.alliedmods.net/showthread.php?t=330200
> 
> or make a separate post, please close the topic here and post on Alliedmodders

How is this off topic? 

Also, after further investigation, I believe it is a bug with the linux build of the game and not the plugin. I have submitted a report to Valve.
