### ISSUE TITLE
Support MySQL 8

### ISSUE THREAD

**Issue by Snakzi** [StAwN74/ckSurf-1.18kd-Release#11]
Hi,

in MySQL, plain passwords are not allowed anymore, it uses "caching_sha2_password". Is there an option to get it to work and not downgrade to 5.7?

kind regards and thank you for your work.

**Comment by Bara** [comment]
https://stackoverflow.com/questions/50169576/mysql-8-0-11-error-connect-to-caching-sha2-password-the-specified-module-could-n
https://www.digitalocean.com/community/questions/how-to-change-caching_sha2_password-to-mysql_native_password-on-a-digitalocean-s-managed-mysql-database
and more with the help of Google.

**Comment by Snakzi** [comment]
well, i know there is a solution. but wouldnt it be better if the plugin would support the new mechanism? plain and encrypted passwords, there is no need to explain which is better.

**Comment by Bara** [comment]
No, that's related to SourceMod. Personally I think it'll never supported by SourceMod.
