### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by brdasma** [StAwN74/ckSurf-1.18kd-Release#12]
I wrote a comment on another of your projects, I dont know why. 
But anyways. I need help with this plugin, please add me on discord Asma#0252.
(Im swedish)

**Comment by freakexeuLow** [comment]
> Asma#252.

hey and if you want to use cksurf, I would advise against it now, as there is currently something better: [https://github.com/surftimer/Surftimer-Official](https://github.com/surftimer/Surftimer-Official)

**Comment by brdasma** [comment]
Alright! Could you help me set it up? Asma#0252 on discord

**Comment by freakexeuLow** [comment]
> Alright! Could you help me set it up? Asma#252 on discord

try it alone, it's all described below what you need or join the SurfTimer Discord, it's there also in the description

**Comment by brdasma** [comment]
> > Alright! Could you help me set it up? Asma#252 on discord
> 
> try it alone, it's all described below what you need or join the SurfTimer Discord, it's there also in the description

I don't get any of it. Could you help me?

**Comment by freakexeuLow** [comment]
> > > Alright! Could you help me set it up? Asma#252 on discord
> > 
> > 
> > try it alone, it's all described below what you need or join the SurfTimer Discord, it's there also in the description
> 
> I don't get any of it. Could you help me?

Then you have to learn it, it's no use if I set it up for you but you don't understand it. Please try it yourself first, it's really not that hard.
