### ISSUE TITLE
Need to Changelevel after server reboot to get Zones back

### ISSUE THREAD

**Issue by ghost** [StAwN74/ckSurf-1.18kd-Release#3]
Hi,

First of all, really great work on this plugin! I just installed it yesterday and it's really great!

When I reboot my server at night (to install updates) I need to make a "changelevel" to get my Zones back.

I use the **ckSurf_slh_rev.smx** (and **sv_hibernate_when_empty 0**)
**Metamod:** Source version 1.10.7-dev
**SourceMod** Version: 1.10.0.6488
**Other plugins:**
01 "Basic Commands" (1.10.0.6488) by AlliedModders LLC
02 "Basic Comm Control" (1.10.0.6488) by AlliedModders LLC
03 "No Blood" (1.0.1) by Bara
04 "Admin File Reader" (1.10.0.6488) by AlliedModders LLC
05 "Admin Menu" (1.10.0.6488) by AlliedModders LLC
06 "Admin Help" (1.10.0.6488) by AlliedModders LLC
07 "Discord API" (0.1.103) by Deathknife
08 "ckSurf" (1.18kd by StAwN) by Elzi
09 "Basic Ban Commands" (1.10.0.6488) by AlliedModders LLC
10 "Fix Hint Color Messages" (1.0.1) by Phoenix (˙·٠●Феникс●٠·˙) and Franc1sco Franug

The ckSurf_slh_rev.smx is from yesterdays build (02/06/20 version). 

**Bonus info:** I use this plugin with MYSQL (Ver 8.0.20-0ubuntu0.20.04.1 for Linux on x86_64)

**Comment by StAwN74** [comment]
Yes, it should be fixed. The only bug remaining for me is the bonus bot on 1st server start: it gets removed very fast and you have only replay bot and info bot. But at next map it's fine.
